### ISSUE TITLE
关于extract_feature_model模型

### ISSUE THREAD

**Issue by YunJiao-Chen** [houzhengzhang/speaker_recognition#3]
您好！ 
1 在您的1-development文件夹中model.py中，extract_feature_model 特征提取模型好像在train.py中没用到呀，那输出的这个模型怎么用呢？
2 可以通过从训练好的模型如spk.h5 中获取到中间特征层，您的checkpoint-00484-0.99_notop.h5模型是否通过该方法呢？
麻烦您解答下，谢谢了

**Comment by houzhengzhang** [comment]
不好意思，最近没看gihub
1.我在utils文件下写了一个sep_model_weight.py脚本，通过这个脚本可以把extract_feature_model 的权重分离出来，然后就可以得到预测特征的模型权重了
2.checkpoint-00484-0.99_notop.h5 是通过sep_model_weight.py脚本得到的。

**Comment by THtanghuan** [comment]
你好，我不太清楚`你`是用spk.h5还是heckpoint-××××-0.××.h5当作最后的模型呢。麻烦回答一下，万分感谢!

**Comment by houzhengzhang** [comment]
我是用checkpoint-00484-0.99_notop.h5作为最后模型的，输出d-vector
