### ISSUE TITLE
注册数据和测试数据

### ISSUE THREAD

**Issue by Fengzhijjin** [houzhengzhang/speaker_recognition#4]
你好, 我正在测试您的项目,我想使用自己的数据用来实验注册和测试,您能告诉我所需的,数据结构吗?

**Comment by zacharyclam** [comment]
我是对aishell的数据集进行vad处理，然后将每段语音切分成一秒长度的片段，输入模型后得到一个特征向量记录下来作为注册集，测试时将测试人的语音输入模型得到特征向量，与注册集里的所有特征向量进行比对，决定拒绝或者接受。
