### ISSUE TITLE
关于模型问题

### ISSUE THREAD

**Issue by qianbudiao6** [houzhengzhang/speaker_recognition#5]
您好，我在实验的时候想要复现原有论文的四层DNN全连接结构，想参考一下您的代码。但是把您代码中的模型更换成
    model.add(Dense(256, input_shape=(3960, )))
    model.add(Activation('relu'))
    model.add(Dropout(0.2))
    model.add(Dense(256))
    model.add(Activation('relu'))
    model.add(Dropout(0.2))
    model.add(Dense(256))
    model.summary()
就是将原有卷积神经网络的输入（99，40）拉伸成（3960，）输入全连接神经网络联合softmax进行分类，但是训练结果训练集和验证集正确率都接近0%，想请教您是哪里的问题，应该怎么改正呢？

**Comment by zacharyclam** [comment]
是不是数据预处理出现问题了，可以先选取少量数据训练看模型能不能过拟合

**Comment by qianbudiao6** [comment]
我在原有的aishell数据库上选取了20个说话人进行测试，按照上面给的输入训练，训练集和验证集也只有25%左右的正确率（没有过拟合，因为训练集正确率一直也没什么提高），但是前面加上一层卷积层conv1d，并将输入重新变为（99，40）之后，训练50个batch左右，准确率就达到了90%，我检查了代码并没有发现问题原因。。。如果第一层为全连接将与数据有关的操作reshape成（3960，），这样的处理是不对的吗？

**Comment by zacharyclam** [comment]
我采用（99，40）输入是把mfcc提取到的特征进行concat得到的，如果reshape成(3960,)可能把某些时序特征破坏掉了
