### ISSUE TITLE
你好 confusion_matrix 这个函数 的功能是什么？是说话人的标签吗？另外 博主，绘制ROC曲线是否可以变种为DET曲线

### ISSUE THREAD

**Issue by quyuquan2019** [houzhengzhang/speaker_recognition#6]

**Comment by zacharyclam** [comment]
confusion_matrix这个函数主要是用于计算混淆矩阵，然后绘制ROC曲线

**Comment by quyuquan2019** [comment]
大佬 是否可以讲解一下 网络的输入  stacked filterbank energy features 是怎么srack。我不是太明白 用40维logbank 和上下文 30ms 10ms 是怎么stack的？

**Comment by houzhengzhang** [comment]
具体细节我忘了，你可以看下https://github.com/houzhengzhang/speaker_recognition/blob/17cbc790c3866379266c9e1105e43dcc51c061c8/code/utils/process_wav.py#L14
这里的处理
